const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Behaviors.Fade,
		C3.Plugins.Mouse,
		C3.Plugins.Text,
		C3.Plugins.Keyboard,
		C3.Plugins.TextBox,
		C3.Plugins.Button,
		C3.Plugins.AJAX,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.TextBox.Acts.SetVisible,
		C3.Plugins.Button.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Health: 0},
	{Bullet: 0},
	{monster: 0},
	{DestroyOutsideLayout: 0},
	{spell: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{BoundToLayout: 0},
	{shooter: 0},
	{Fade: 0},
	{sparkflash: 0},
	{Mouse: 0},
	{pontos: 0},
	{saude: 0},
	{RankingDeJogadores: 0},
	{Keyboard: 0},
	{GameOver: 0},
	{playerInput: 0},
	{buttonSubmit: 0},
	{AJAX: 0},
	{commandText: 0},
	{Score: 0},
	{ScoreDB: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	monster: class extends self.ISpriteInstance {},
	spell: class extends self.ISpriteInstance {},
	shooter: class extends self.ISpriteInstance {},
	sparkflash: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	pontos: class extends self.ITextInstance {},
	saude: class extends self.ITextInstance {},
	RankingDeJogadores: class extends self.ITextInstance {},
	Keyboard: class extends self.IInstance {},
	GameOver: class extends self.ITextInstance {},
	playerInput: class extends self.ITextInputInstance {},
	buttonSubmit: class extends self.IButtonInstance {},
	AJAX: class extends self.IInstance {},
	commandText: class extends self.ITextInstance {}
}